name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        env:
          KEY: ~/.ssh/id_rsa
          USER: ec2-user  # Adjust this to your EC2 instance's username
          HOST: ${{ secrets.HOST }}  # Ensure this is the correct hostname or IP
        run: |
          echo "Connecting to $USER@$HOST"
          ssh -o StrictHostKeyChecking=no -i $KEY $USER@$HOST 'bash -s' < ./deploy/deploy.sh
