name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: scp -r -o StrictHostKeyChecking=no . ec2-user@${{ secrets.HOST }}:/home/ec2-user/T1-nestjs-hello-world

    - name: Execute deployment script
      run: ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.HOST }} 'bash /home/ec2-user/T1-nestjs-hello-world/deploy/deploy.sh'
